[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "4c29e519014708395e1c23682fd3d78509d8a650"
os = "macos"

    [[kdb_c_api.download]]
    sha256 = "82bd87de0910e288535da1805d464d68e7634b70d98f1e9b8944035ce76ac344"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.aarch64-apple-darwin.tar.gz"
[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "6b69afa5a88d78aa81384260f27aa8bec5c2966d"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "ddc7d10dcf3edf97412628bc880d85233209ca6d352bcea166ef6b0afbf2544a"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.aarch64-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "d7ffdfe716bf27e425c9a69c5c13f166ca7176b8"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "0ec2dbba5e6d37c33ac8d42cebd91e72ae256f859b5fcdb78b8e3ba1b8a44fb5"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.aarch64-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "e025a85b8bd048bf7c8c6d6606b9d5d2164c7874"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "6204a52b9f103d4c658cb5461b240d144fe1aff4dc38a506802fc903cd228a16"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.i686-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "eacfbfdfc1d4c733bd9d81038969a2e22f7ec44b"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "4af7f0b513a7681eb02c3e28d98c93465d9ee2cfdfeef4dfef826fa8815d2afb"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.i686-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "5ced08ce0f348cc42125f240d141c136f87652f7"
os = "windows"

    [[kdb_c_api.download]]
    sha256 = "ef8790c6510b9d589897952042c770cba2c539e34822279c1b5b1005961d0b5e"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.i686-w64-mingw32.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "ff8c265dfc158bdd7b67c6f0d8218f3a5552e298"
os = "macos"

    [[kdb_c_api.download]]
    sha256 = "af967e31400deea638a9f6fe0cf020bac48597776ce2064b452a78f4e760138c"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.x86_64-apple-darwin.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "634ebed8e91d841fa7c5760f09a9ae9c04777259"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "15a3936908c85b32666a880ab2aff77593fe304246a014ab492fc706192ce985"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.x86_64-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "0a42bc2e06721be9706d1279434d803c02062d9d"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "1bcaa4873f9122691dd065c6942ce2471ef5b9d06b3874e68cb5e5f9a9d506c3"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.x86_64-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "990b91c096d61f6c40b45172a6edb63d38198ad0"
os = "windows"

    [[kdb_c_api.download]]
    sha256 = "4a673da19c9ec7d741736f514eddf458db094cd35c5b35ef63eaa37569d86563"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2022.9.3+0/kdb_c_api.v2022.9.3.x86_64-w64-mingw32.tar.gz"
