[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "bb3c629131976123ebcf35a7b5805433a9c06f58"
os = "macos"

    [[kdb_c_api.download]]
    sha256 = "77b9bef57373f2888e62b0a4e347252815b3c47911dce17b2a32a3de6f222ac1"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.aarch64-apple-darwin.tar.gz"
[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "08c0ea1da5f9dcd38558f76baae0b7b6dd4ff3c1"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "1342438fe5732630094c4431600ce49bc9612110be0c499d3f1716f22fe63a28"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.aarch64-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "aarch64"
git-tree-sha1 = "0f64ca65b3169f1ed5cb7a60488950ef647f6d2b"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "e01418d148cf8af75295df56e991e845c7cb392eb9d8589fe105d62bb64f2ef2"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.aarch64-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "4dad3914adabb3d926870500d89ff4e2d627bbd5"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "a156d4acba52eb8bacda33a8743981f2194bed856df164fba4b7c3db19538d7f"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.i686-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "1b3aa19c0633795ea0b889e22e2c2fb19fb12d02"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "370e623f06446f4b2bba2da7257926a7830ec7843fcb91274c76ac35eb844f3b"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.i686-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "i686"
git-tree-sha1 = "3f912107ee34f167ad1aefc9a9da0583bc9aad2c"
os = "windows"

    [[kdb_c_api.download]]
    sha256 = "d4d344eddb70cfe6c954cb05a085e4e3e0291b63d914895773b3956372161217"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.i686-w64-mingw32.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "31e7651d831f6625d14c3811353535487441067c"
os = "macos"

    [[kdb_c_api.download]]
    sha256 = "86df6c0c0df3cc0c5f163da6356e9426a22f0461ef82f003d58b89db4c9cce16"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.x86_64-apple-darwin.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "45589c61c6aaff9f32e80cec8670a2b3ec26e2f4"
libc = "glibc"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "8a9b7a7f10cba3da81e400233bfa794adb34993a44dcef6ec2dfefa56804c88b"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.x86_64-linux-gnu.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "cdb9c867f75d765886462c2a857bee65ee784069"
libc = "musl"
os = "linux"

    [[kdb_c_api.download]]
    sha256 = "5911cf44d3f82e52400fae5241823ad52f6477783cb3705920864420968a923e"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.x86_64-linux-musl.tar.gz"
[[kdb_c_api]]
arch = "x86_64"
git-tree-sha1 = "4cc4fc030152ead9c6e7eb8ee3253859675e1f35"
os = "windows"

    [[kdb_c_api.download]]
    sha256 = "8f639cbd6ad95f8a6c11f032cd9aef4aa9e151ecd77ffafce4d6d76a39172667"
    url = "https://github.com/JuliaBinaryWrappers/kdb_c_api_jll.jl/releases/download/kdb_c_api-v2024.10.21+0/kdb_c_api.v2024.10.21.x86_64-w64-mingw32.tar.gz"
