# Autogenerated wrapper script for kdb_c_api_jll for aarch64-apple-darwin
export kdb_c_so

JLLWrappers.@generate_wrapper_header("kdb_c_api")
JLLWrappers.@declare_library_product(kdb_c_so, "@rpath/c.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        kdb_c_so,
        "lib/c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
